// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.7.3
// - protoc             v3.19.4
// source: api.proto

package api

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationV1Services = "/v1.V1/Services"

type V1HTTPServer interface {
	Services(context.Context, *emptypb.Empty) (*ServicesResp, error)
}

func RegisterV1HTTPServer(s *http.Server, srv V1HTTPServer) {
	r := s.Route("/")
	r.GET("/services", _V1_Services0_HTTP_Handler(srv))
}

func _V1_Services0_HTTP_Handler(srv V1HTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in emptypb.Empty
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationV1Services)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Services(ctx, req.(*emptypb.Empty))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ServicesResp)
		return ctx.Result(200, reply)
	}
}

type V1HTTPClient interface {
	Services(ctx context.Context, req *emptypb.Empty, opts ...http.CallOption) (rsp *ServicesResp, err error)
}

type V1HTTPClientImpl struct {
	cc *http.Client
}

func NewV1HTTPClient(client *http.Client) V1HTTPClient {
	return &V1HTTPClientImpl{client}
}

func (c *V1HTTPClientImpl) Services(ctx context.Context, in *emptypb.Empty, opts ...http.CallOption) (*ServicesResp, error) {
	var out ServicesResp
	pattern := "/services"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationV1Services))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
